name: test

on:
  push

jobs:
  shelltest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: sh -x .github/workflows/test.sh

